name: Deploy Shiny App

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependenciese
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rsconnect
            any::remotes
            any::cpp11
            any::isoband
          needs: |
            website

      - name: Install package
        run: |
          # Install from GitHub to get the correct "RemoteType: github" metadata
          # We use force=TRUE to ensure it reinstalls the very latest push
          Rscript -e 'remotes::install_github("cfjdoedens/binompoiscont", force = TRUE, upgrade = "never")'
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e "
            rsconnect::setAccountInfo(
              name = '${{ secrets.SHINYAPPS_NAME }}',
              token = '${{ secrets.SHINYAPPS_TOKEN }}',
              secret = '${{ secrets.SHINYAPPS_SECRET }}'
            )

            # Deploy the specific folder
            rsconnect::deployApp(
              appDir = 'inst/shiny/binompoiscont',
              appName = 'binompoiscont',
              forceUpdate = TRUE
            )
          "
